
exclude:
  - "/vendor/"
  - "README.md"
  - "LICENSE.md"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Ina Fister
subtitle: Regie und Produktion
# Base URL of site. It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
# baseurl: "/" # the subpath of your site
url: "http://graphicore.github.io" # the base hostname & protocol for your site
# baseurl: "/testdrive"


collections:
- projekte

detach:  false
port:    4000
host:    127.0.0.1

