
exclude:
  - "/vendor/"
  - "README.md"
  - "LICENSE.md"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Site settings
title: Ina Fister
subtitle: Regie und Producing
# Base URL of site. It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
# baseurl: "/" # the subpath of your site
url: "http://inafister.de" # the base hostname & protocol for your site
# baseurl: "/testdrive"


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      pageClass: "default"
  -
    scope:
      type: "projekte"
    values:
      active: "projekte"
      pageClass: "projekt"
      js_include_photoswipe: true


collections:
  projekte:
    output: true
    permalink: /projekt/:path.html

detach:  false
port:    4000
host:    127.0.0.1

